on: [push, pull_request]
name: build
env:
  GO111MODULE: on
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: bin/build.sh
      shell: bash
    - name: Test
      run: bin/test.sh
      shell: bash
    - name: Generate Code Coverage
      run: bin/coverage.sh
      shell: bash
    - name: Send to Coveralls
      uses: shogo82148/actions-goveralls@v1
      if: matrix.platform == 'ubuntu-latest'
      with:
        path-to-profile: coverage.out
    - name: Upload Code Coverage
      uses: actions/upload-artifact@v1
      if: matrix.platform == 'ubuntu-latest'
      with:
        name: coverage
        path: coverage.html
    - name: Upload SystemLink CLI
      uses: actions/upload-artifact@v1
      if: matrix.platform == 'ubuntu-latest'
      with:
        name: systemlink-cli
        path: build/
  publish:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.CLIDeployAccessKey }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.CLIDeploySecretKey }}
    steps:
    - name: Download SystemLink CLI
      uses: actions/download-artifact@v1
      with:
        name: systemlink-cli
    - name: Publish SystemLink CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        zip -r systemlink-cli.zip systemlink-cli/*
        aws/dist/aws s3 cp systemlink-cli.zip s3://systemlink-releases/systemlink-cli/systemlink-cli.zip
      shell: bash